networks:
  bracket_lan:
    driver: bridge

volumes:
  bracket_pg_data:
  bracket_static_data:

services:
  bracket:
    container_name: bracket
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: DEVELOPMENT
      CORS_ORIGINS: http://localhost:3000
      PG_DSN: postgresql://bracket_dev:bracket_dev@postgres:5432/bracket_dev
      SERVE_FRONTEND: false
      API_PREFIX: ''
    build:
      context: ./backend
    networks:
      - bracket_lan
    ports:
      - 8400:8400
    restart: unless-stopped
    volumes:
      - bracket_static_data:/app/static

  frontend:
    container_name: bracket-frontend
    depends_on:
      - bracket
    build:
      context: ./frontend
    networks:
      - bracket_lan
    ports:
      - 3000:3000
    restart: unless-stopped

  postgres:
    environment:
      POSTGRES_DB: bracket_dev
      POSTGRES_PASSWORD: bracket_dev
      POSTGRES_USER: bracket_dev
    image: postgres:16
    networks:
      - bracket_lan
    restart: always
    volumes:
      - bracket_pg_data:/var/lib/postgresql/data
